### ISSUE TITLE
Bug in Documentation > Type Inference

### ISSUE THREAD

**Issue by skiwi2** [groovy/groovy-website#65] opened 2015-05-15 18:43 UTC
As seen in the image below there is (possibly) a bug here:

![groovydocerror3](https://cloud.githubusercontent.com/assets/2961606/7659534/efcde308-fb42-11e4-981d-2b4f329e9173.png)

The bug can be found on the following page: http://docs.groovy-lang.org/latest/html/documentation/#type-inference

Please see attached the following Ideone: https://ideone.com/Evao2b

**Comment by dmahapatro** [comment] 2015-05-15 18:48
Your choice of humane touch in all the issues is stupendous. ;)

**Comment by glaforge** [comment] 2015-05-15 19:21
What would be even nicer would be to have pull requests as well fixing those findings ;-)

**Comment by melix** [comment] 2015-05-15 19:35
Thanks, the problem is in fact in the Groovy project itself, here: https://github.com/apache/incubator-groovy/blob/master/src/spec/doc/core-semantics.adoc#L1617-1617

**Comment by PascalSchumacher** [comment] 2015-06-10 15:43
Thanks for reporting!

This will be fixed in the next version:

http://docs.groovy-lang.org/next/html/documentation/#type-inference

**Comment by paulk-asert** [comment] 2015-06-11 10:18
Fixed.

**Closed by paulk-asert** 2015-06-11 10:18 UTC
